//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace CozyComfortWindowsApp.CozyComfortServiceRef {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CozyComfortServiceSoap", Namespace="http://tempuri.org/")]
    public partial class CozyComfortService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Manufacturer_GetBlanketsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Manufacturer_AddBlanketOperationCompleted;
        
        private System.Threading.SendOrPostCallback Manufacturer_UpdateBlanketOperationCompleted;
        
        private System.Threading.SendOrPostCallback Manufacturer_DeleteBlanketOperationCompleted;
        
        private System.Threading.SendOrPostCallback Manufacturer_GetStockRequestsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Manufacturer_ApproveRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback Manufacturer_RejectRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback Distributor_GetStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback Distributor_AddStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback Distributor_UpdateStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback Distributor_DeleteStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback Distributor_GetSellerOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback Distributor_RequestStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback Distributor_FulfillOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback Distributor_CancelOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback Seller_GetStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback Seller_AddStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback Seller_UpdateStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback Seller_DeleteStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback Seller_CheckOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback Seller_PlaceOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback Seller_GetAvailableBlanketsOperationCompleted;
        
        private System.Threading.SendOrPostCallback Admin_GetAllUsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback Admin_AddUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback Admin_UpdateUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback Admin_DeleteUserOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CozyComfortService() {
            this.Url = global::CozyComfortWindowsApp.Properties.Settings.Default.CozyComfortWindowsApp_CozyComfortServiceRef_CozyComfortService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event Manufacturer_GetBlanketsCompletedEventHandler Manufacturer_GetBlanketsCompleted;
        
        /// <remarks/>
        public event Manufacturer_AddBlanketCompletedEventHandler Manufacturer_AddBlanketCompleted;
        
        /// <remarks/>
        public event Manufacturer_UpdateBlanketCompletedEventHandler Manufacturer_UpdateBlanketCompleted;
        
        /// <remarks/>
        public event Manufacturer_DeleteBlanketCompletedEventHandler Manufacturer_DeleteBlanketCompleted;
        
        /// <remarks/>
        public event Manufacturer_GetStockRequestsCompletedEventHandler Manufacturer_GetStockRequestsCompleted;
        
        /// <remarks/>
        public event Manufacturer_ApproveRequestCompletedEventHandler Manufacturer_ApproveRequestCompleted;
        
        /// <remarks/>
        public event Manufacturer_RejectRequestCompletedEventHandler Manufacturer_RejectRequestCompleted;
        
        /// <remarks/>
        public event Distributor_GetStockCompletedEventHandler Distributor_GetStockCompleted;
        
        /// <remarks/>
        public event Distributor_AddStockCompletedEventHandler Distributor_AddStockCompleted;
        
        /// <remarks/>
        public event Distributor_UpdateStockCompletedEventHandler Distributor_UpdateStockCompleted;
        
        /// <remarks/>
        public event Distributor_DeleteStockCompletedEventHandler Distributor_DeleteStockCompleted;
        
        /// <remarks/>
        public event Distributor_GetSellerOrdersCompletedEventHandler Distributor_GetSellerOrdersCompleted;
        
        /// <remarks/>
        public event Distributor_RequestStockCompletedEventHandler Distributor_RequestStockCompleted;
        
        /// <remarks/>
        public event Distributor_FulfillOrderCompletedEventHandler Distributor_FulfillOrderCompleted;
        
        /// <remarks/>
        public event Distributor_CancelOrderCompletedEventHandler Distributor_CancelOrderCompleted;
        
        /// <remarks/>
        public event Seller_GetStockCompletedEventHandler Seller_GetStockCompleted;
        
        /// <remarks/>
        public event Seller_AddStockCompletedEventHandler Seller_AddStockCompleted;
        
        /// <remarks/>
        public event Seller_UpdateStockCompletedEventHandler Seller_UpdateStockCompleted;
        
        /// <remarks/>
        public event Seller_DeleteStockCompletedEventHandler Seller_DeleteStockCompleted;
        
        /// <remarks/>
        public event Seller_CheckOrdersCompletedEventHandler Seller_CheckOrdersCompleted;
        
        /// <remarks/>
        public event Seller_PlaceOrderCompletedEventHandler Seller_PlaceOrderCompleted;
        
        /// <remarks/>
        public event Seller_GetAvailableBlanketsCompletedEventHandler Seller_GetAvailableBlanketsCompleted;
        
        /// <remarks/>
        public event Admin_GetAllUsersCompletedEventHandler Admin_GetAllUsersCompleted;
        
        /// <remarks/>
        public event Admin_AddUserCompletedEventHandler Admin_AddUserCompleted;
        
        /// <remarks/>
        public event Admin_UpdateUserCompletedEventHandler Admin_UpdateUserCompleted;
        
        /// <remarks/>
        public event Admin_DeleteUserCompletedEventHandler Admin_DeleteUserCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Login(string username, string password) {
            object[] results = this.Invoke("Login", new object[] {
                        username,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password) {
            this.LoginAsync(username, password, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string username, string password, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        username,
                        password}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Manufacturer_GetBlankets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Blanket[] Manufacturer_GetBlankets() {
            object[] results = this.Invoke("Manufacturer_GetBlankets", new object[0]);
            return ((Blanket[])(results[0]));
        }
        
        /// <remarks/>
        public void Manufacturer_GetBlanketsAsync() {
            this.Manufacturer_GetBlanketsAsync(null);
        }
        
        /// <remarks/>
        public void Manufacturer_GetBlanketsAsync(object userState) {
            if ((this.Manufacturer_GetBlanketsOperationCompleted == null)) {
                this.Manufacturer_GetBlanketsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnManufacturer_GetBlanketsOperationCompleted);
            }
            this.InvokeAsync("Manufacturer_GetBlankets", new object[0], this.Manufacturer_GetBlanketsOperationCompleted, userState);
        }
        
        private void OnManufacturer_GetBlanketsOperationCompleted(object arg) {
            if ((this.Manufacturer_GetBlanketsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Manufacturer_GetBlanketsCompleted(this, new Manufacturer_GetBlanketsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Manufacturer_AddBlanket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Manufacturer_AddBlanket(Blanket blanket) {
            object[] results = this.Invoke("Manufacturer_AddBlanket", new object[] {
                        blanket});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Manufacturer_AddBlanketAsync(Blanket blanket) {
            this.Manufacturer_AddBlanketAsync(blanket, null);
        }
        
        /// <remarks/>
        public void Manufacturer_AddBlanketAsync(Blanket blanket, object userState) {
            if ((this.Manufacturer_AddBlanketOperationCompleted == null)) {
                this.Manufacturer_AddBlanketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnManufacturer_AddBlanketOperationCompleted);
            }
            this.InvokeAsync("Manufacturer_AddBlanket", new object[] {
                        blanket}, this.Manufacturer_AddBlanketOperationCompleted, userState);
        }
        
        private void OnManufacturer_AddBlanketOperationCompleted(object arg) {
            if ((this.Manufacturer_AddBlanketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Manufacturer_AddBlanketCompleted(this, new Manufacturer_AddBlanketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Manufacturer_UpdateBlanket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Manufacturer_UpdateBlanket(Blanket blanket) {
            object[] results = this.Invoke("Manufacturer_UpdateBlanket", new object[] {
                        blanket});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Manufacturer_UpdateBlanketAsync(Blanket blanket) {
            this.Manufacturer_UpdateBlanketAsync(blanket, null);
        }
        
        /// <remarks/>
        public void Manufacturer_UpdateBlanketAsync(Blanket blanket, object userState) {
            if ((this.Manufacturer_UpdateBlanketOperationCompleted == null)) {
                this.Manufacturer_UpdateBlanketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnManufacturer_UpdateBlanketOperationCompleted);
            }
            this.InvokeAsync("Manufacturer_UpdateBlanket", new object[] {
                        blanket}, this.Manufacturer_UpdateBlanketOperationCompleted, userState);
        }
        
        private void OnManufacturer_UpdateBlanketOperationCompleted(object arg) {
            if ((this.Manufacturer_UpdateBlanketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Manufacturer_UpdateBlanketCompleted(this, new Manufacturer_UpdateBlanketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Manufacturer_DeleteBlanket", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Manufacturer_DeleteBlanket(int blanketId) {
            object[] results = this.Invoke("Manufacturer_DeleteBlanket", new object[] {
                        blanketId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Manufacturer_DeleteBlanketAsync(int blanketId) {
            this.Manufacturer_DeleteBlanketAsync(blanketId, null);
        }
        
        /// <remarks/>
        public void Manufacturer_DeleteBlanketAsync(int blanketId, object userState) {
            if ((this.Manufacturer_DeleteBlanketOperationCompleted == null)) {
                this.Manufacturer_DeleteBlanketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnManufacturer_DeleteBlanketOperationCompleted);
            }
            this.InvokeAsync("Manufacturer_DeleteBlanket", new object[] {
                        blanketId}, this.Manufacturer_DeleteBlanketOperationCompleted, userState);
        }
        
        private void OnManufacturer_DeleteBlanketOperationCompleted(object arg) {
            if ((this.Manufacturer_DeleteBlanketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Manufacturer_DeleteBlanketCompleted(this, new Manufacturer_DeleteBlanketCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Manufacturer_GetStockRequests", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public StockRequest[] Manufacturer_GetStockRequests() {
            object[] results = this.Invoke("Manufacturer_GetStockRequests", new object[0]);
            return ((StockRequest[])(results[0]));
        }
        
        /// <remarks/>
        public void Manufacturer_GetStockRequestsAsync() {
            this.Manufacturer_GetStockRequestsAsync(null);
        }
        
        /// <remarks/>
        public void Manufacturer_GetStockRequestsAsync(object userState) {
            if ((this.Manufacturer_GetStockRequestsOperationCompleted == null)) {
                this.Manufacturer_GetStockRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnManufacturer_GetStockRequestsOperationCompleted);
            }
            this.InvokeAsync("Manufacturer_GetStockRequests", new object[0], this.Manufacturer_GetStockRequestsOperationCompleted, userState);
        }
        
        private void OnManufacturer_GetStockRequestsOperationCompleted(object arg) {
            if ((this.Manufacturer_GetStockRequestsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Manufacturer_GetStockRequestsCompleted(this, new Manufacturer_GetStockRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Manufacturer_ApproveRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Manufacturer_ApproveRequest(int requestId) {
            object[] results = this.Invoke("Manufacturer_ApproveRequest", new object[] {
                        requestId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Manufacturer_ApproveRequestAsync(int requestId) {
            this.Manufacturer_ApproveRequestAsync(requestId, null);
        }
        
        /// <remarks/>
        public void Manufacturer_ApproveRequestAsync(int requestId, object userState) {
            if ((this.Manufacturer_ApproveRequestOperationCompleted == null)) {
                this.Manufacturer_ApproveRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnManufacturer_ApproveRequestOperationCompleted);
            }
            this.InvokeAsync("Manufacturer_ApproveRequest", new object[] {
                        requestId}, this.Manufacturer_ApproveRequestOperationCompleted, userState);
        }
        
        private void OnManufacturer_ApproveRequestOperationCompleted(object arg) {
            if ((this.Manufacturer_ApproveRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Manufacturer_ApproveRequestCompleted(this, new Manufacturer_ApproveRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Manufacturer_RejectRequest", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Manufacturer_RejectRequest(int requestId) {
            object[] results = this.Invoke("Manufacturer_RejectRequest", new object[] {
                        requestId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Manufacturer_RejectRequestAsync(int requestId) {
            this.Manufacturer_RejectRequestAsync(requestId, null);
        }
        
        /// <remarks/>
        public void Manufacturer_RejectRequestAsync(int requestId, object userState) {
            if ((this.Manufacturer_RejectRequestOperationCompleted == null)) {
                this.Manufacturer_RejectRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnManufacturer_RejectRequestOperationCompleted);
            }
            this.InvokeAsync("Manufacturer_RejectRequest", new object[] {
                        requestId}, this.Manufacturer_RejectRequestOperationCompleted, userState);
        }
        
        private void OnManufacturer_RejectRequestOperationCompleted(object arg) {
            if ((this.Manufacturer_RejectRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Manufacturer_RejectRequestCompleted(this, new Manufacturer_RejectRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Distributor_GetStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Stock[] Distributor_GetStock(int distributorId) {
            object[] results = this.Invoke("Distributor_GetStock", new object[] {
                        distributorId});
            return ((Stock[])(results[0]));
        }
        
        /// <remarks/>
        public void Distributor_GetStockAsync(int distributorId) {
            this.Distributor_GetStockAsync(distributorId, null);
        }
        
        /// <remarks/>
        public void Distributor_GetStockAsync(int distributorId, object userState) {
            if ((this.Distributor_GetStockOperationCompleted == null)) {
                this.Distributor_GetStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDistributor_GetStockOperationCompleted);
            }
            this.InvokeAsync("Distributor_GetStock", new object[] {
                        distributorId}, this.Distributor_GetStockOperationCompleted, userState);
        }
        
        private void OnDistributor_GetStockOperationCompleted(object arg) {
            if ((this.Distributor_GetStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Distributor_GetStockCompleted(this, new Distributor_GetStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Distributor_AddStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Distributor_AddStock(Stock stockItem) {
            object[] results = this.Invoke("Distributor_AddStock", new object[] {
                        stockItem});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Distributor_AddStockAsync(Stock stockItem) {
            this.Distributor_AddStockAsync(stockItem, null);
        }
        
        /// <remarks/>
        public void Distributor_AddStockAsync(Stock stockItem, object userState) {
            if ((this.Distributor_AddStockOperationCompleted == null)) {
                this.Distributor_AddStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDistributor_AddStockOperationCompleted);
            }
            this.InvokeAsync("Distributor_AddStock", new object[] {
                        stockItem}, this.Distributor_AddStockOperationCompleted, userState);
        }
        
        private void OnDistributor_AddStockOperationCompleted(object arg) {
            if ((this.Distributor_AddStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Distributor_AddStockCompleted(this, new Distributor_AddStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Distributor_UpdateStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Distributor_UpdateStock(int stockId, int newQuantity) {
            object[] results = this.Invoke("Distributor_UpdateStock", new object[] {
                        stockId,
                        newQuantity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Distributor_UpdateStockAsync(int stockId, int newQuantity) {
            this.Distributor_UpdateStockAsync(stockId, newQuantity, null);
        }
        
        /// <remarks/>
        public void Distributor_UpdateStockAsync(int stockId, int newQuantity, object userState) {
            if ((this.Distributor_UpdateStockOperationCompleted == null)) {
                this.Distributor_UpdateStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDistributor_UpdateStockOperationCompleted);
            }
            this.InvokeAsync("Distributor_UpdateStock", new object[] {
                        stockId,
                        newQuantity}, this.Distributor_UpdateStockOperationCompleted, userState);
        }
        
        private void OnDistributor_UpdateStockOperationCompleted(object arg) {
            if ((this.Distributor_UpdateStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Distributor_UpdateStockCompleted(this, new Distributor_UpdateStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Distributor_DeleteStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Distributor_DeleteStock(int stockId) {
            object[] results = this.Invoke("Distributor_DeleteStock", new object[] {
                        stockId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Distributor_DeleteStockAsync(int stockId) {
            this.Distributor_DeleteStockAsync(stockId, null);
        }
        
        /// <remarks/>
        public void Distributor_DeleteStockAsync(int stockId, object userState) {
            if ((this.Distributor_DeleteStockOperationCompleted == null)) {
                this.Distributor_DeleteStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDistributor_DeleteStockOperationCompleted);
            }
            this.InvokeAsync("Distributor_DeleteStock", new object[] {
                        stockId}, this.Distributor_DeleteStockOperationCompleted, userState);
        }
        
        private void OnDistributor_DeleteStockOperationCompleted(object arg) {
            if ((this.Distributor_DeleteStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Distributor_DeleteStockCompleted(this, new Distributor_DeleteStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Distributor_GetSellerOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Order[] Distributor_GetSellerOrders() {
            object[] results = this.Invoke("Distributor_GetSellerOrders", new object[0]);
            return ((Order[])(results[0]));
        }
        
        /// <remarks/>
        public void Distributor_GetSellerOrdersAsync() {
            this.Distributor_GetSellerOrdersAsync(null);
        }
        
        /// <remarks/>
        public void Distributor_GetSellerOrdersAsync(object userState) {
            if ((this.Distributor_GetSellerOrdersOperationCompleted == null)) {
                this.Distributor_GetSellerOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDistributor_GetSellerOrdersOperationCompleted);
            }
            this.InvokeAsync("Distributor_GetSellerOrders", new object[0], this.Distributor_GetSellerOrdersOperationCompleted, userState);
        }
        
        private void OnDistributor_GetSellerOrdersOperationCompleted(object arg) {
            if ((this.Distributor_GetSellerOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Distributor_GetSellerOrdersCompleted(this, new Distributor_GetSellerOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Distributor_RequestStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Distributor_RequestStock(StockRequest request) {
            object[] results = this.Invoke("Distributor_RequestStock", new object[] {
                        request});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Distributor_RequestStockAsync(StockRequest request) {
            this.Distributor_RequestStockAsync(request, null);
        }
        
        /// <remarks/>
        public void Distributor_RequestStockAsync(StockRequest request, object userState) {
            if ((this.Distributor_RequestStockOperationCompleted == null)) {
                this.Distributor_RequestStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDistributor_RequestStockOperationCompleted);
            }
            this.InvokeAsync("Distributor_RequestStock", new object[] {
                        request}, this.Distributor_RequestStockOperationCompleted, userState);
        }
        
        private void OnDistributor_RequestStockOperationCompleted(object arg) {
            if ((this.Distributor_RequestStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Distributor_RequestStockCompleted(this, new Distributor_RequestStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Distributor_FulfillOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Distributor_FulfillOrder(int orderId, int distributorId) {
            object[] results = this.Invoke("Distributor_FulfillOrder", new object[] {
                        orderId,
                        distributorId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Distributor_FulfillOrderAsync(int orderId, int distributorId) {
            this.Distributor_FulfillOrderAsync(orderId, distributorId, null);
        }
        
        /// <remarks/>
        public void Distributor_FulfillOrderAsync(int orderId, int distributorId, object userState) {
            if ((this.Distributor_FulfillOrderOperationCompleted == null)) {
                this.Distributor_FulfillOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDistributor_FulfillOrderOperationCompleted);
            }
            this.InvokeAsync("Distributor_FulfillOrder", new object[] {
                        orderId,
                        distributorId}, this.Distributor_FulfillOrderOperationCompleted, userState);
        }
        
        private void OnDistributor_FulfillOrderOperationCompleted(object arg) {
            if ((this.Distributor_FulfillOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Distributor_FulfillOrderCompleted(this, new Distributor_FulfillOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Distributor_CancelOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Distributor_CancelOrder(int orderId) {
            object[] results = this.Invoke("Distributor_CancelOrder", new object[] {
                        orderId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Distributor_CancelOrderAsync(int orderId) {
            this.Distributor_CancelOrderAsync(orderId, null);
        }
        
        /// <remarks/>
        public void Distributor_CancelOrderAsync(int orderId, object userState) {
            if ((this.Distributor_CancelOrderOperationCompleted == null)) {
                this.Distributor_CancelOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDistributor_CancelOrderOperationCompleted);
            }
            this.InvokeAsync("Distributor_CancelOrder", new object[] {
                        orderId}, this.Distributor_CancelOrderOperationCompleted, userState);
        }
        
        private void OnDistributor_CancelOrderOperationCompleted(object arg) {
            if ((this.Distributor_CancelOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Distributor_CancelOrderCompleted(this, new Distributor_CancelOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Seller_GetStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Stock[] Seller_GetStock(int sellerId) {
            object[] results = this.Invoke("Seller_GetStock", new object[] {
                        sellerId});
            return ((Stock[])(results[0]));
        }
        
        /// <remarks/>
        public void Seller_GetStockAsync(int sellerId) {
            this.Seller_GetStockAsync(sellerId, null);
        }
        
        /// <remarks/>
        public void Seller_GetStockAsync(int sellerId, object userState) {
            if ((this.Seller_GetStockOperationCompleted == null)) {
                this.Seller_GetStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeller_GetStockOperationCompleted);
            }
            this.InvokeAsync("Seller_GetStock", new object[] {
                        sellerId}, this.Seller_GetStockOperationCompleted, userState);
        }
        
        private void OnSeller_GetStockOperationCompleted(object arg) {
            if ((this.Seller_GetStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Seller_GetStockCompleted(this, new Seller_GetStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Seller_AddStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Seller_AddStock(Stock stockItem) {
            object[] results = this.Invoke("Seller_AddStock", new object[] {
                        stockItem});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Seller_AddStockAsync(Stock stockItem) {
            this.Seller_AddStockAsync(stockItem, null);
        }
        
        /// <remarks/>
        public void Seller_AddStockAsync(Stock stockItem, object userState) {
            if ((this.Seller_AddStockOperationCompleted == null)) {
                this.Seller_AddStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeller_AddStockOperationCompleted);
            }
            this.InvokeAsync("Seller_AddStock", new object[] {
                        stockItem}, this.Seller_AddStockOperationCompleted, userState);
        }
        
        private void OnSeller_AddStockOperationCompleted(object arg) {
            if ((this.Seller_AddStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Seller_AddStockCompleted(this, new Seller_AddStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Seller_UpdateStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Seller_UpdateStock(int stockId, int newQuantity) {
            object[] results = this.Invoke("Seller_UpdateStock", new object[] {
                        stockId,
                        newQuantity});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Seller_UpdateStockAsync(int stockId, int newQuantity) {
            this.Seller_UpdateStockAsync(stockId, newQuantity, null);
        }
        
        /// <remarks/>
        public void Seller_UpdateStockAsync(int stockId, int newQuantity, object userState) {
            if ((this.Seller_UpdateStockOperationCompleted == null)) {
                this.Seller_UpdateStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeller_UpdateStockOperationCompleted);
            }
            this.InvokeAsync("Seller_UpdateStock", new object[] {
                        stockId,
                        newQuantity}, this.Seller_UpdateStockOperationCompleted, userState);
        }
        
        private void OnSeller_UpdateStockOperationCompleted(object arg) {
            if ((this.Seller_UpdateStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Seller_UpdateStockCompleted(this, new Seller_UpdateStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Seller_DeleteStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Seller_DeleteStock(int stockId) {
            object[] results = this.Invoke("Seller_DeleteStock", new object[] {
                        stockId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Seller_DeleteStockAsync(int stockId) {
            this.Seller_DeleteStockAsync(stockId, null);
        }
        
        /// <remarks/>
        public void Seller_DeleteStockAsync(int stockId, object userState) {
            if ((this.Seller_DeleteStockOperationCompleted == null)) {
                this.Seller_DeleteStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeller_DeleteStockOperationCompleted);
            }
            this.InvokeAsync("Seller_DeleteStock", new object[] {
                        stockId}, this.Seller_DeleteStockOperationCompleted, userState);
        }
        
        private void OnSeller_DeleteStockOperationCompleted(object arg) {
            if ((this.Seller_DeleteStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Seller_DeleteStockCompleted(this, new Seller_DeleteStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Seller_CheckOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Order[] Seller_CheckOrders(int sellerId) {
            object[] results = this.Invoke("Seller_CheckOrders", new object[] {
                        sellerId});
            return ((Order[])(results[0]));
        }
        
        /// <remarks/>
        public void Seller_CheckOrdersAsync(int sellerId) {
            this.Seller_CheckOrdersAsync(sellerId, null);
        }
        
        /// <remarks/>
        public void Seller_CheckOrdersAsync(int sellerId, object userState) {
            if ((this.Seller_CheckOrdersOperationCompleted == null)) {
                this.Seller_CheckOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeller_CheckOrdersOperationCompleted);
            }
            this.InvokeAsync("Seller_CheckOrders", new object[] {
                        sellerId}, this.Seller_CheckOrdersOperationCompleted, userState);
        }
        
        private void OnSeller_CheckOrdersOperationCompleted(object arg) {
            if ((this.Seller_CheckOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Seller_CheckOrdersCompleted(this, new Seller_CheckOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Seller_PlaceOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Seller_PlaceOrder(Order order) {
            object[] results = this.Invoke("Seller_PlaceOrder", new object[] {
                        order});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Seller_PlaceOrderAsync(Order order) {
            this.Seller_PlaceOrderAsync(order, null);
        }
        
        /// <remarks/>
        public void Seller_PlaceOrderAsync(Order order, object userState) {
            if ((this.Seller_PlaceOrderOperationCompleted == null)) {
                this.Seller_PlaceOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeller_PlaceOrderOperationCompleted);
            }
            this.InvokeAsync("Seller_PlaceOrder", new object[] {
                        order}, this.Seller_PlaceOrderOperationCompleted, userState);
        }
        
        private void OnSeller_PlaceOrderOperationCompleted(object arg) {
            if ((this.Seller_PlaceOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Seller_PlaceOrderCompleted(this, new Seller_PlaceOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Seller_GetAvailableBlankets", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Blanket[] Seller_GetAvailableBlankets() {
            object[] results = this.Invoke("Seller_GetAvailableBlankets", new object[0]);
            return ((Blanket[])(results[0]));
        }
        
        /// <remarks/>
        public void Seller_GetAvailableBlanketsAsync() {
            this.Seller_GetAvailableBlanketsAsync(null);
        }
        
        /// <remarks/>
        public void Seller_GetAvailableBlanketsAsync(object userState) {
            if ((this.Seller_GetAvailableBlanketsOperationCompleted == null)) {
                this.Seller_GetAvailableBlanketsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSeller_GetAvailableBlanketsOperationCompleted);
            }
            this.InvokeAsync("Seller_GetAvailableBlankets", new object[0], this.Seller_GetAvailableBlanketsOperationCompleted, userState);
        }
        
        private void OnSeller_GetAvailableBlanketsOperationCompleted(object arg) {
            if ((this.Seller_GetAvailableBlanketsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Seller_GetAvailableBlanketsCompleted(this, new Seller_GetAvailableBlanketsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Admin_GetAllUsers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public User[] Admin_GetAllUsers() {
            object[] results = this.Invoke("Admin_GetAllUsers", new object[0]);
            return ((User[])(results[0]));
        }
        
        /// <remarks/>
        public void Admin_GetAllUsersAsync() {
            this.Admin_GetAllUsersAsync(null);
        }
        
        /// <remarks/>
        public void Admin_GetAllUsersAsync(object userState) {
            if ((this.Admin_GetAllUsersOperationCompleted == null)) {
                this.Admin_GetAllUsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdmin_GetAllUsersOperationCompleted);
            }
            this.InvokeAsync("Admin_GetAllUsers", new object[0], this.Admin_GetAllUsersOperationCompleted, userState);
        }
        
        private void OnAdmin_GetAllUsersOperationCompleted(object arg) {
            if ((this.Admin_GetAllUsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Admin_GetAllUsersCompleted(this, new Admin_GetAllUsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Admin_AddUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Admin_AddUser(User user) {
            object[] results = this.Invoke("Admin_AddUser", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Admin_AddUserAsync(User user) {
            this.Admin_AddUserAsync(user, null);
        }
        
        /// <remarks/>
        public void Admin_AddUserAsync(User user, object userState) {
            if ((this.Admin_AddUserOperationCompleted == null)) {
                this.Admin_AddUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdmin_AddUserOperationCompleted);
            }
            this.InvokeAsync("Admin_AddUser", new object[] {
                        user}, this.Admin_AddUserOperationCompleted, userState);
        }
        
        private void OnAdmin_AddUserOperationCompleted(object arg) {
            if ((this.Admin_AddUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Admin_AddUserCompleted(this, new Admin_AddUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Admin_UpdateUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Admin_UpdateUser(User user) {
            object[] results = this.Invoke("Admin_UpdateUser", new object[] {
                        user});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Admin_UpdateUserAsync(User user) {
            this.Admin_UpdateUserAsync(user, null);
        }
        
        /// <remarks/>
        public void Admin_UpdateUserAsync(User user, object userState) {
            if ((this.Admin_UpdateUserOperationCompleted == null)) {
                this.Admin_UpdateUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdmin_UpdateUserOperationCompleted);
            }
            this.InvokeAsync("Admin_UpdateUser", new object[] {
                        user}, this.Admin_UpdateUserOperationCompleted, userState);
        }
        
        private void OnAdmin_UpdateUserOperationCompleted(object arg) {
            if ((this.Admin_UpdateUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Admin_UpdateUserCompleted(this, new Admin_UpdateUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Admin_DeleteUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Admin_DeleteUser(int userId) {
            object[] results = this.Invoke("Admin_DeleteUser", new object[] {
                        userId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Admin_DeleteUserAsync(int userId) {
            this.Admin_DeleteUserAsync(userId, null);
        }
        
        /// <remarks/>
        public void Admin_DeleteUserAsync(int userId, object userState) {
            if ((this.Admin_DeleteUserOperationCompleted == null)) {
                this.Admin_DeleteUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAdmin_DeleteUserOperationCompleted);
            }
            this.InvokeAsync("Admin_DeleteUser", new object[] {
                        userId}, this.Admin_DeleteUserOperationCompleted, userState);
        }
        
        private void OnAdmin_DeleteUserOperationCompleted(object arg) {
            if ((this.Admin_DeleteUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Admin_DeleteUserCompleted(this, new Admin_DeleteUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Blanket {
        
        private int blanketIDField;
        
        private string nameField;
        
        private string descriptionField;
        
        private string materialField;
        
        private decimal priceField;
        
        /// <remarks/>
        public int BlanketID {
            get {
                return this.blanketIDField;
            }
            set {
                this.blanketIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Material {
            get {
                return this.materialField;
            }
            set {
                this.materialField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User {
        
        private int userIDField;
        
        private string usernameField;
        
        private string passwordHashField;
        
        private string roleField;
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string PasswordHash {
            get {
                return this.passwordHashField;
            }
            set {
                this.passwordHashField = value;
            }
        }
        
        /// <remarks/>
        public string Role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Order {
        
        private int orderIDField;
        
        private int sellerIDField;
        
        private string sellerNameField;
        
        private int blanketIDField;
        
        private string blanketNameField;
        
        private int quantityField;
        
        private System.DateTime orderDateField;
        
        private string statusField;
        
        /// <remarks/>
        public int OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        public int SellerID {
            get {
                return this.sellerIDField;
            }
            set {
                this.sellerIDField = value;
            }
        }
        
        /// <remarks/>
        public string SellerName {
            get {
                return this.sellerNameField;
            }
            set {
                this.sellerNameField = value;
            }
        }
        
        /// <remarks/>
        public int BlanketID {
            get {
                return this.blanketIDField;
            }
            set {
                this.blanketIDField = value;
            }
        }
        
        /// <remarks/>
        public string BlanketName {
            get {
                return this.blanketNameField;
            }
            set {
                this.blanketNameField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime OrderDate {
            get {
                return this.orderDateField;
            }
            set {
                this.orderDateField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Stock {
        
        private int stockIDField;
        
        private int blanketIDField;
        
        private string blanketNameField;
        
        private int ownerIDField;
        
        private int quantityField;
        
        private System.DateTime lastUpdatedField;
        
        private decimal priceField;
        
        /// <remarks/>
        public int StockID {
            get {
                return this.stockIDField;
            }
            set {
                this.stockIDField = value;
            }
        }
        
        /// <remarks/>
        public int BlanketID {
            get {
                return this.blanketIDField;
            }
            set {
                this.blanketIDField = value;
            }
        }
        
        /// <remarks/>
        public string BlanketName {
            get {
                return this.blanketNameField;
            }
            set {
                this.blanketNameField = value;
            }
        }
        
        /// <remarks/>
        public int OwnerID {
            get {
                return this.ownerIDField;
            }
            set {
                this.ownerIDField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StockRequest {
        
        private int requestIDField;
        
        private int distributorIDField;
        
        private string distributorNameField;
        
        private int blanketIDField;
        
        private string blanketNameField;
        
        private int quantityField;
        
        private System.DateTime requestDateField;
        
        private string statusField;
        
        /// <remarks/>
        public int RequestID {
            get {
                return this.requestIDField;
            }
            set {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        public int DistributorID {
            get {
                return this.distributorIDField;
            }
            set {
                this.distributorIDField = value;
            }
        }
        
        /// <remarks/>
        public string DistributorName {
            get {
                return this.distributorNameField;
            }
            set {
                this.distributorNameField = value;
            }
        }
        
        /// <remarks/>
        public int BlanketID {
            get {
                return this.blanketIDField;
            }
            set {
                this.blanketIDField = value;
            }
        }
        
        /// <remarks/>
        public string BlanketName {
            get {
                return this.blanketNameField;
            }
            set {
                this.blanketNameField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Manufacturer_GetBlanketsCompletedEventHandler(object sender, Manufacturer_GetBlanketsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Manufacturer_GetBlanketsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Manufacturer_GetBlanketsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Blanket[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Blanket[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Manufacturer_AddBlanketCompletedEventHandler(object sender, Manufacturer_AddBlanketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Manufacturer_AddBlanketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Manufacturer_AddBlanketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Manufacturer_UpdateBlanketCompletedEventHandler(object sender, Manufacturer_UpdateBlanketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Manufacturer_UpdateBlanketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Manufacturer_UpdateBlanketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Manufacturer_DeleteBlanketCompletedEventHandler(object sender, Manufacturer_DeleteBlanketCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Manufacturer_DeleteBlanketCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Manufacturer_DeleteBlanketCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Manufacturer_GetStockRequestsCompletedEventHandler(object sender, Manufacturer_GetStockRequestsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Manufacturer_GetStockRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Manufacturer_GetStockRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public StockRequest[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((StockRequest[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Manufacturer_ApproveRequestCompletedEventHandler(object sender, Manufacturer_ApproveRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Manufacturer_ApproveRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Manufacturer_ApproveRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Manufacturer_RejectRequestCompletedEventHandler(object sender, Manufacturer_RejectRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Manufacturer_RejectRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Manufacturer_RejectRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Distributor_GetStockCompletedEventHandler(object sender, Distributor_GetStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Distributor_GetStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Distributor_GetStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Stock[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Stock[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Distributor_AddStockCompletedEventHandler(object sender, Distributor_AddStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Distributor_AddStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Distributor_AddStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Distributor_UpdateStockCompletedEventHandler(object sender, Distributor_UpdateStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Distributor_UpdateStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Distributor_UpdateStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Distributor_DeleteStockCompletedEventHandler(object sender, Distributor_DeleteStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Distributor_DeleteStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Distributor_DeleteStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Distributor_GetSellerOrdersCompletedEventHandler(object sender, Distributor_GetSellerOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Distributor_GetSellerOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Distributor_GetSellerOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Order[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Order[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Distributor_RequestStockCompletedEventHandler(object sender, Distributor_RequestStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Distributor_RequestStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Distributor_RequestStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Distributor_FulfillOrderCompletedEventHandler(object sender, Distributor_FulfillOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Distributor_FulfillOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Distributor_FulfillOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Distributor_CancelOrderCompletedEventHandler(object sender, Distributor_CancelOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Distributor_CancelOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Distributor_CancelOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Seller_GetStockCompletedEventHandler(object sender, Seller_GetStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Seller_GetStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Seller_GetStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Stock[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Stock[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Seller_AddStockCompletedEventHandler(object sender, Seller_AddStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Seller_AddStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Seller_AddStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Seller_UpdateStockCompletedEventHandler(object sender, Seller_UpdateStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Seller_UpdateStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Seller_UpdateStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Seller_DeleteStockCompletedEventHandler(object sender, Seller_DeleteStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Seller_DeleteStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Seller_DeleteStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Seller_CheckOrdersCompletedEventHandler(object sender, Seller_CheckOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Seller_CheckOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Seller_CheckOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Order[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Order[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Seller_PlaceOrderCompletedEventHandler(object sender, Seller_PlaceOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Seller_PlaceOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Seller_PlaceOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Seller_GetAvailableBlanketsCompletedEventHandler(object sender, Seller_GetAvailableBlanketsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Seller_GetAvailableBlanketsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Seller_GetAvailableBlanketsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Blanket[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Blanket[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Admin_GetAllUsersCompletedEventHandler(object sender, Admin_GetAllUsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Admin_GetAllUsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Admin_GetAllUsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public User[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((User[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Admin_AddUserCompletedEventHandler(object sender, Admin_AddUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Admin_AddUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Admin_AddUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Admin_UpdateUserCompletedEventHandler(object sender, Admin_UpdateUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Admin_UpdateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Admin_UpdateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    public delegate void Admin_DeleteUserCompletedEventHandler(object sender, Admin_DeleteUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Admin_DeleteUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Admin_DeleteUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591